# Etapa 1: Node.js base image
FROM node:20-alpine AS base

# Establecer directorio de trabajo
WORKDIR /usr/src/app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Instalar nodemon globalmente para desarrollo
RUN npm install -g @nestjs/cli nodemon

# Copiar todo el código fuente
COPY . .

# Exponer el puerto en el que la app se ejecutará
EXPOSE 3000

# Comando para iniciar la aplicación en desarrollo
CMD ["npm", "run", "start:dev"]
